export const pricingPlans = [
  {
    id: "startup",
    nameKey: "pricing.startup.name",
    subtitleKey: "pricing.startup.subtitle",
    price: {
      monthly: "3,500,000",
      quarterly: "9,975,000",
      yearly: "35,700,000",
    },
    credits: "3,500 credits",
    creditsKey: "pricing.month",
    features: [
      "Kết nối: Facebook, Instagram, TikTok",
      "Giới hạn 3 kênh/page mỗi nền tảng",
      "Báo cáo hiệu suất đa nền tảng",
      "Quản trị nội dung đa nền tảng",
      "Quản trị quảng cáo đa nền tảng",
      "Hỗ trợ qua Ticket",
    ],
    featuresEn: [
      "Connect: Facebook, Instagram, TikTok",
      "Limit 3 channels/pages per platform",
      "Multi-platform performance reports",
      "Multi-platform content management",
      "Multi-platform advertising management",
      "Ticket support",
    ],
    ctaKey: "pricing.cta.start",
    popular: false,
    featured: false,
  },
  {
    id: "growth",
    nameKey: "pricing.growth.name",
    badgeKey: "pricing.popular",
    subtitleKey: "pricing.growth.subtitle",
    price: {
      monthly: "6,900,000",
      quarterly: "19,665,000",
      yearly: "70,380,000",
    },
    credits: "7,500 credits (Bonus 1,000)",
    creditsKey: "pricing.month",
    features: [
      "Kết nối: Facebook, Instagram, TikTok, LinkedIn, X, YouTube",
      "Không giới hạn kênh/page trên nền tảng",
      "Báo cáo hiệu suất đa nền tảng",
      "AI Phân tích nội dung & đề xuất chỉnh sửa",
      "AI Phân tích quảng cáo & đề xuất tối ưu",
      "AI Phân tích chỉ số nền tảng",
      "Quản trị nội dung đa nền tảng",
      "Quản trị quảng cáo đa nền tảng",
      "Hỗ trợ ưu tiên 24/7",
    ],
    featuresEn: [
      "Connect: Facebook, Instagram, TikTok, LinkedIn, X, YouTube",
      "Unlimited channels/pages per platform",
      "Multi-platform performance reports",
      "AI Content analysis & editing suggestions",
      "AI Advertising analysis & optimization",
      "AI Platform metrics analysis",
      "Multi-platform content management",
      "Multi-platform advertising management",
      "24/7 priority support",
    ],
    ctaKey: "pricing.cta.start",
    popular: true,
    featured: true,
  },
  {
    id: "enterprise",
    nameKey: "pricing.enterprise.name",
    subtitleKey: "pricing.enterprise.subtitle",
    price: {
      monthly: "pricing.contact",
      quarterly: "pricing.contact",
      yearly: "pricing.contact",
    },
    credits: "Unlimited credits",
    creditsKey: null,
    features: [
      "Bao gồm tất cả tính năng gói Growth",
      "Tất cả tính năng nâng cao (AI, Báo cáo, Phân quyền)",
      "Dedicated Server (không chia sẻ tài nguyên)",
      "Kết nối không giới hạn kênh",
      "Lưu trữ video không giới hạn, không hết hạn",
      "Model AI sử dụng riêng, chi phí tách biệt",
      "SLA 99.9% uptime",
      "Hỗ trợ 1:1 chuyên biệt",
    ],
    featuresEn: [
      "All Growth plan features included",
      "All advanced features (AI, Reports, Permissions)",
      "Dedicated Server (no resource sharing)",
      "Unlimited channel connections",
      "Unlimited video storage, never expires",
      "Dedicated AI models, separate costs",
      "SLA 99.9% uptime",
      "1:1 dedicated support",
    ],
    ctaKey: "pricing.cta.contact",
    popular: false,
    featured: false,
  },
];

export default pricingPlans;
